name: zenonine_lints
version: 0.0.1
description: Lint rules for Dart and Flutter used in ZenoNine's packages.
homepage: https://github.com/zenonine/flutter_lints
repository: https://github.com/zenonine/flutter_lints
documentation: https://github.com/zenonine/flutter_lints
issue_tracker: https://github.com/zenonine/flutter_lints/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  very_good_analysis: ^2.4.0